### PR TITLE
Update gleam to v0.4

### LINKED ISSUE #90: update gleam to v0.4
It is necessary for servo/webrender#771.

### PR DESCRIPTION
**Pull request by sotaroikeda**
Fixes #90.

### CODE REVIEW

**Comment by emilio** [comment]
LGTM, thanks!

**Comment by sotaroikeda** [comment]
Thank you!

**Comment by sotaroikeda** [comment]
@emilio, can you update crate to "0.8.2"?

**Comment by emilio** [comment]
Done, sorry!

**Comment by sotaroikeda** [comment]
Thanks!

**Pull request merged**
