### PR TITLE
Cleanup matrix and run tests in CI

### PR DESCRIPTION
**Pull request by sagudev**
I discovered in https://github.com/servo/surfman/pull/321 that we do not run any test in CI, so I cleaned up matrix, run tests on native platforms (use wayland/x11 emulation on linux) and fix examples (mostly by removing support for rwh05 that wasn't working anyway). I think it should be safe to remove rwh05 as winit only supports rwh06, but that should be done as a followup.

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by sagudev** [comment]
I've added https://github.com/servo/surfman/pull/323/commits/f7280b645be9ae7e7dd2a36023103c50a7c8453b that ignores some bad results from angle.

BTW I do not have permissions to land in surfman :(

**Comment by jdm** [comment]
I just fixed the repo settings; the Maintainers team only had read access for some reason.

**Comment by sagudev** [comment]
> I just fixed the repo settings; the Maintainers team only had read access for some reason.

I still have: slika

**Comment by jdm** [comment]
I have now added the maintainers team to the list of authorized users.

**Comment by sagudev** [comment]
It works!

**Pull request merged**
