### PR TITLE
Update winit to version 0.29

### PR DESCRIPTION
**Pull request by jdm**

### CODE REVIEW

**Comment by atouchet** [comment]
winit can also be updated in https://github.com/servo/surfman/blob/master/android-example/rust/Cargo.toml as well.

**Comment by mrobinson** [comment]
I tried to revive this, but I think it might be simpler just to remove winit support in favor of `raw_window_handle` (https://github.com/servo/surfman/pull/271).

@jdm Any thoughts on that approach?

**Comment by jdm** [comment]
Oh, that never even occurred to me. I think that's probably the way to go!

**Comment by mrobinson** [comment]
@jdm thank you!

This is obsoleted by https://github.com/servo/surfman/pull/271.

**Pull request closed without merging**
