### PR TITLE
Make it possible to force GLES usage on Linux

### PR DESCRIPTION
**Pull request by webbeef**

### CODE REVIEW

**Comment by jdm** [comment]
Have you verified that this actually works? For example, there's another instance of this in device.rs in the same directory.

**Comment by webbeef** [comment]
Yes, on a Pinephone Pro this worked with the initial patch, but I updated it with your suggestion.

**Review by jdm — APPROVED** [review]
This seems like a reasonable quick fix to expose the functionality.

**Comment by webbeef** [comment]
Thanks! Do you plan to do a new release in the near future?

**Comment by jdm** [comment]
Yeah, I'll publish 0.9.6 once this merges.

**Pull request merged**
