### PR TITLE
Use cstr literals where possible

### PR DESCRIPTION
**Pull request by jschwe**
Convert usage of byte str and normal str with a `\0` to cstr literals where possible

### CODE REVIEW

**Comment by mrobinson** [comment]
This seems fine though it seems the build is failing on Windows.

**Comment by jdm** [comment]
I suspect c strings are i8 on windows? It's a common cross-platform error.

**Comment by jschwe** [comment]
> I suspect c strings are i8 on windows? It's a common cross-platform error.

The nice thing about `CStr` is that the `as_ptr()` method documents that it [returns `*const c_char`]（https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.as_ptr. This allows us to remove a lot of the casts in the window specific code.

While removing those needless casts, I stumbled a bit over [CreateWindowExA](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexa) accepting a `u16` encoded in a pointer type and added a comment in the source code explaining it.

**Review by jdm — APPROVED** [review]
These changes are great! Thanks for cleaning up the code.

**Pull request merged**
