### PR TITLE
Bump rust nightly to 2022-08-27

### PR DESCRIPTION
**Pull request by becmer**
Fix workflow for 2021 edition on nightly

### CODE REVIEW

**Comment by becmer** [comment]
btw. @jdm is there any reason for use of specific version instead of latest one or this is just tech debt?

**Comment by jdm** [comment]
I believe it was pinned to avoid a compiler bug in nightly that was preventing merges.

**Comment by becmer** [comment]
Could you trigger it once again please? It seems that the build is flaky because some networking issues on GH side.

**Pull request merged**
