### PR TITLE
Add link to gl library if necessary

### PR DESCRIPTION
**Pull request by sotaroikeda**
This fixes issue #84

Added link to gl library on linux and windows.

### CODE REVIEW

**Comment by sotaroikeda** [comment]
Add links to a library that is used by StaticGenerator

**Comment by emilio** [comment]
Why doesn't this link to the GL framework in OSX or EGL in android?

**Comment by sotaroikeda** [comment]
I did not add it because StaticGenerator is not used on mac. But instead, cgl is used and cgl defines functions of  GL framework :(

It seems better to revert linking to gleam, since gleam is used out side of offscreen_gl_context. Another crates expects the library is linked by gleam.

gleam<-cgl<-glutin
                  <-offscreen_gl_context
                  <-winit

**Comment by sotaroikeda** [comment]
I did not add EGL in android since the link was already requested by the following.
  https://github.com/emilio/rust-offscreen-rendering-context/blob/master/build.rs#L22

**Comment by sotaroikeda** [comment]
I chose to add link at offscreen_gl_context. I updated a patch as to add link on mac. On android case, link to EGL is already exist in build.rs.

**Comment by sotaroikeda** [comment]
@emilio, can you review again? Thanks.

**Comment by emilio** [comment]
r=me, thanks!

**Comment by glennw** [comment]
@sotaroikeda @emilio I'm working on the WR update in Servo - but getting a link error on android due to it trying to link libGL - any ideas where this might be coming from? The log is http://build.servo.org/builders/android/builds/5902/steps/compile/logs/stdio from https://github.com/servo/servo/pull/16073#issuecomment-288307095.

**Comment by sotaroikeda** [comment]
It seems to be addressed now by https://github.com/emilio/rust-offscreen-rendering-context/commit/7e00056554269e28826d5ac4b57b0438f7f6f3f2

**Pull request merged**
