### PR TITLE
Add a cargo feature to force EGL on windows

### PR DESCRIPTION
**Pull request by jdm**
Depends on https://github.com/servo/mozangle/pull/21.

This change is [Reviewable](https://reviewable.io/reviews/servo/rust-offscreen-rendering-context/136)

### CODE REVIEW

**Comment by jdm** [comment]
This is untested so far.

**Comment by paulrouget** [comment]
This appears to work. As in, no link to opengl32. Thanks.

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
