### PR TITLE
Update winit to 0.22

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by iamralpht** [comment]
I also had a try at this: https://github.com/iamralpht/surfman/tree/winit-0.22.1
I tested on macOS, Linux X11 and Linux Wayland. No idea if it works on Windows.

**Comment by Eijebong** [comment]
Well it compiles on windows with mine and I somehow missed the one platform I'm using. But I'm updating it in servo too so it should catch all the remaining failures (hence the draft mode)

**Comment by ArturKovacs** [comment]
I'm looking forward to seeing this merged. It would be nice for: https://github.com/ArturKovacs/emulsion/issues/85

Is there any way I can help with this?

**Comment by borup3** [comment]
Can this get another winit bump to 0.22.2? I'm more than willing to aid in testing.

**Comment by jdm** [comment]
0.22.1 just means that's the minimum version. Any downstream consumer of surman can update to 0.22.x where x>=1 without any changes to surfman.

**Comment by pcwalton** [comment]
Is this ready to go?

**Comment by jdm** [comment]
I think eijebong wanted to wait until the corresponding winit servo update demonstrated that the changes were working correctly.

**Comment by Eijebong** [comment]
Yeah sorry, haven't had time at all to work on that. I have patches working for servo with that but they require unsafe to circumvent some limitation of winit. There's a better way to do so which requires changing how webxr inits surfman and that's way more involved. Hopefully I can get some motivation soon to finish that work...

**Comment by nicoabie** [comment]
@Eijebong I offer a mac to test if this is working :)

**Comment by OvermindDL1** [comment]
Is anything required to help get this update out?

**Comment by jdm** [comment]
We wanted to have the changes ready in servo/servo before merging this, since otherwise it blocks being able to easily make any changes to surfman until that work is complete.

**Comment by atouchet** [comment]
This was finished in #223.

**Pull request closed without merging**
