### PR TITLE
rust-geom API changes

### PR DESCRIPTION
**Pull request by frewsxcv**
Shouldn't be merged until https://github.com/servo/rust-geom/pull/81 has merged

### CODE REVIEW

**Comment by emilio** [comment]
There are a few more changes that need to be done in platform-specific code, by I'll take care of them :)

I'll PR your PR and merge this when the changes land :P

**Comment by frewsxcv** [comment]
https://github.com/servo/rust-layers/pull/178 and https://github.com/servo/rust-geom/pull/81 have been merged

**Comment by frewsxcv** [comment]
> There are a few more changes that need to be done in platform-specific code, by I'll take care of them :)

I think I got all of them in my latest force push

**Comment by emilio** [comment]
Yep, looks good :)
Thanks!

**Pull request merged**
