### PR TITLE
Support creating windowed surfaces on UWP

### PR DESCRIPTION
**Pull request by asajeffrey**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by jdm** [comment]
```
error[E0308]: mismatched types

   --> surfman\src\platform\windows\angle\connection.rs:125:50

    |

125 |             Ok(NativeWidget { egl_native_window: hwnd })

    |                                                  ^^^^ expected enum `std::ffi::c_void`, found enum `winapi::shared::windef::HWND__`

    |

    = note: expected raw pointer `*const std::ffi::c_void`

               found raw pointer `*mut winapi::shared::windef::HWND__`
```

**Comment by asajeffrey** [comment]
Oops, didn't cherry-pick as much as I needed from the servo-surfmanup branch. @bors-servo r=jdm

**Pull request merged**
