### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by asajeffrey**
Major version bump

### CODE REVIEW

**Comment by asajeffrey** [comment]
Should probably land after #187

**Review by jdm — APPROVED** [review]

**Comment by atouchet** [comment]
Can some dependencies be updated before the version is bumped? More specifically updating gl/gl_generator and the macOS dependencies like cocoa would help towards deduping these in Servo.

**Comment by asajeffrey** [comment]
@atouchet care to submit a PR? I don't want to delay this too much, since it's a blocker on landing webxr layer management.

**Comment by asajeffrey** [comment]
OK, doing an experiment to see how easy updating deps would be: https://travis-ci.com/github/asajeffrey/surfman/builds/173035469

It looks like updating gl_generator is straightforward, but updating the mac dependencies causes build errors: https://travis-ci.com/github/asajeffrey/surfman/jobs/353617288

I propose to update gl_generator, but leave the Mac dependencies as-is for right now.

**Comment by atouchet** [comment]
@asajeffrey sounds good. winit is blocking getting rid of most of the macOS dependency dupes for now anyways.

**Comment by asajeffrey** [comment]
Filed #190.

**Comment by asajeffrey** [comment]
Also, we should hold off on this version bump until I address https://github.com/servo/surfman/pull/187#discussion_r445658500

**Comment by asajeffrey** [comment]
Filed #191, when that merges hopefully we can do the version bump.

**Pull request merged**
