### PR TITLE
Update Dependencies & Rust Edition

### PR DESCRIPTION
**Pull request by Snowiiii**
Update Dependencies & Rust Edition

I ask you to realease a new surfman version as soon as possible because I would like to Update winit to v0.26.1 in servo

### CODE REVIEW

**Comment by Snowiiii** [comment]
I use winit v0.26.1 because its the last version without the sctk-adwaita patch(https://github.com/rust-windowing/winit/commit/f09259f6deb6f9dd99b8e116bc6edbb65cfb51e3)
that does bad things(https://github.com/servo/servo/issues/29157)

**Comment by jdm** [comment]
We prefer to merge and release after the changes to servo are ready. You can use your fork for testing with a [cargo override](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html).

**Comment by Snowiiii** [comment]
So you want i pull the servo changes with cargo override

**Comment by jdm** [comment]
The process is:
* Don't update surfman version, but make other necessary changes 
* Push surfman changes to a GitHub branch (done)
* Use cargo override in servo to replace the crates.io version of surfman with your GitHub branch
* Test that servo runs as expected locally
* Push changes to servo fork, test changes in CI

**Pull request closed without merging**
